[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/__/auth/*"
  to = "https://shaivika-lms-ai.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/events/evt-001"
  to = "/events/GITHUB"
  status = 301
  force = true

[[redirects]]
  from = "/events/evt-002"
  to = "/events/PYTHON"
  status = 301
  force = true

[[redirects]]
  from = "/events/evt-003"
  to = "/events/JAVA"
  status = 301
  force = true

[[redirects]]
  from = "/events/evt-004"
  to = "/events/GENERATIVE%20AI"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
